SELECT DISTINCT SALUNO.RA,
                PPESSOA.NOME       AS 'NOME DO ALUNO',
                SMATRICPL.CODTURMA AS 'TURMA',
                1                  AS 'TOTAL'
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
       JOIN PPESSOA
         ON PPESSOA.CODIGO = BHISTORICO.CODPESSOA
       JOIN SALUNO
         ON PPESSOA.CODIGO = SALUNO.CODPESSOA
       JOIN SMATRICPL
         ON SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA
            AND SMATRICPL.RA = SALUNO.RA
       JOIN SPLETIVO(NOLOCK)
         ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
       JOIN STURMADISC (NOLOCK)
         ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
            AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
            AND STURMADISC.CODTURMA = SMATRICPL.CODTURMA
       JOIN SHABILITACAOFILIAL(NOLOCK)
         ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
            AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
WHERE  BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND SHABILITACAOFILIAL.CODFILIAL = 01
       AND SPLETIVO.CODPERLET = '2023/1'
       AND SHABILITACAOFILIAL.CODTIPOCURSO = 01
ORDER  BY 2
