WITH PeriodData AS (
    SELECT 
        CASE 
            WHEN STURMADISC.CODTURMA LIKE 'MED%' THEN 1
            WHEN STURMADISC.CODTURMA LIKE 'M2%' THEN 2
            WHEN STURMADISC.CODTURMA LIKE 'M3%' THEN 3
            WHEN STURMADISC.CODTURMA LIKE 'M4%' THEN 4
            WHEN STURMADISC.CODTURMA LIKE 'M5%' THEN 5
            WHEN STURMADISC.CODTURMA LIKE 'M6%' THEN 6
            WHEN STURMADISC.CODTURMA LIKE 'M7%' THEN 7
            WHEN STURMADISC.CODTURMA LIKE 'M8%' THEN 8
            WHEN STURMADISC.CODTURMA LIKE 'M9%' THEN 9
            WHEN STURMADISC.CODTURMA LIKE 'M10%' THEN 10
            WHEN STURMADISC.CODTURMA LIKE 'M11%' THEN 11
            WHEN STURMADISC.CODTURMA LIKE 'M12%' THEN 12
        END AS PeriodNumber,
        'PERIODO - ' + STURMADISC.CODTURMA AS 'PERIODO',
        COUNT(DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
    JOIN STURMADISC ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
        AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
    JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
    JOIN SMATRICPL ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
    WHERE SHABILITACAOFILIAL.CODCURSO = '03'
        AND SMATRICPL.CODSTATUS NOT IN (28, 10)
        AND (
            STURMADISC.CODTURMA LIKE 'MED%'
            OR STURMADISC.CODTURMA LIKE 'M2%'
            OR STURMADISC.CODTURMA LIKE 'M3%'
            OR STURMADISC.CODTURMA LIKE 'M4%'
            OR STURMADISC.CODTURMA LIKE 'M5%'
            OR STURMADISC.CODTURMA LIKE 'M6%'
            OR STURMADISC.CODTURMA LIKE 'M7%'
            OR STURMADISC.CODTURMA LIKE 'M8%'
            OR STURMADISC.CODTURMA LIKE 'M9%'
            OR STURMADISC.CODTURMA LIKE 'M10%'
            OR STURMADISC.CODTURMA LIKE 'M11%'
            OR STURMADISC.CODTURMA LIKE 'M12%'
        )
   GROUP BY  STURMADISC.CODTURMA
)
SELECT '1º PERIODO - 2023/1' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 1
UNION
SELECT '2º PERIODO - 2023/2' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 2
UNION
SELECT '3º PERIODO - 2023/1' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 3
UNION
SELECT '4º PERIODO - 2023/2' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 4
UNION
SELECT '5° PERIODO - 2023/1' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 5
UNION
SELECT '6º PERIODO - 2023/2' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 6
UNION
SELECT '7º PERIODO - 2023/1' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 7
UNION
SELECT '8º PERIODO - 2023/2' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 8
UNION
SELECT '9º PERIODO - 2023/1' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 9
UNION
SELECT '10º PERIODO - 2023/2' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 10
UNION
SELECT '11º PERIODO - 2023/1' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 11
UNION
SELECT '12º PERIODO - 2023/2' AS 'PERIODO', MATRICULADOS FROM PeriodData WHERE PeriodNumber = 12;

SELECT 