SELECT DISTINCT SALUNO.RA, PPESSOA.NOME FROM SALUNO 
    RIGHT JOIN SDOCALUNO ON
        SDOCALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
    JOIN SHABILITACAOALUNO (NOLOCK)
        ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
            AND SHABILITACAOALUNO.RA = SALUNO.RA
    JOIN SHABILITACAOFILIAL (NOLOCK)
        ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
            AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    JOIN SCURSO (NOLOCK)
        ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
    JOIN PPESSOA (NOLOCK)
        ON PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE SALUNO.RA LIKE '23-1%'
    AND SCURSO.CODCURSO = '03'
    AND SHABILITACAOFILIAL.CODFILIAL = 01
ORDER BY PPESSOA.NOME