SELECT 
    PPESSOA.NOME,
    CASE 
        WHEN PPESSOA.TELEFONE1 IS NULL OR PPESSOA.TELEFONE1 = '' THEN 'Não Preenchido'
        ELSE PPESSOA.TELEFONE1
    END AS  'TELEFONE 1',
    CASE 
        WHEN PPESSOA.TELEFONE2 IS NULL OR PPESSOA.TELEFONE2 = '' THEN 'Não Preenchido'
        ELSE PPESSOA.TELEFONE2
    END AS  'TELEFONE 2',
    CASE 
        WHEN PPESSOA.TELEFONE3 IS NULL OR PPESSOA.TELEFONE3 = '' THEN 'Não Preenchido'
        ELSE PPESSOA.TELEFONE3
    END AS  'TELEFONE 3',
    PPESSOA.EMAIL,
    convert(varchar, SHABILITACAOALUNO.DTCOLACAOGRAU, 105) AS 'DATA DE COLAÇÃO',
    SCURSO.NOME
FROM SHABILITACAOALUNO
    JOIN SALUNO
        ON SALUNO.RA = SHABILITACAOALUNO.RA AND 
        SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
    JOIN PPESSOA
        ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    JOIN SHABILITACAOFILIAL	
        ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA AND
        SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    JOIN SCURSO
        ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND 
            SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
WHERE 
    DTCOLACAOGRAU <= '2022/06/30' AND 
    DTCOLACAOGRAU >= '2021/07/31'
GROUP BY 
    SCURSO.CODCURSO,
    PPESSOA.NOME,
    PPESSOA.TELEFONE1,
    PPESSOA.TELEFONE2,
    PPESSOA.TELEFONE3,
    PPESSOA.EMAIL,
    SHABILITACAOALUNO.DTCOLACAOGRAU,
    SCURSO.NOME
ORDER BY SCURSO.CODCURSO
