SELECT     1 AS ORD,
'1º PERIODO - 2023/1' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 102
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
    AND STURMADISC.CODTURMA IN ('MED1GDA', 'MED1DDA','MED1BDA', 'MED1ADA')
UNION
SELECT  2 AS ORD,
'2º PERIODO - 2023/2' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 110
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M2GDA','M2DDA','M2BDA','M2ADA')
UNION
SELECT  3 AS ORD,
'3º PERIODO - 2023/1' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 102
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M3GDA', 'M3DDA','M3BDA', 'M3ADA', 'M3ADB')
UNION
SELECT  4 AS ORD,
'4º PERIODO - 2023/2' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 110
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M4GDA','M4DDA','M4BDA','M4ADA')
UNION
SELECT 5 AS ORD,
'5° PERIODO - 2023/1' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 102
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M5GDA', 'M5DDA','M5BDA', 'M5ADB', 'M5ADA')
UNION
SELECT 6 AS ORD, 
'6º PERIODO - 2023/2' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 110
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M6GDA','M6DDA','M6BDA','M6ADA')
UNION
SELECT  7 AS ORD,
'7º PERIODO - 2023/1' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 102
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M7GDA', 'M7DDA','M7BDA', 'M7ADA')
UNION
SELECT  8 AS ORD,
'8º PERIODO - 2023/2' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 110
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M8GDA','M8DDA','M8BDA','M8ADA')
UNION
SELECT 9 AS ORD,'9º PERIODO - 2023/1' AS 'PERIODO', 

COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 102
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M11IGG9','M11IGG8','M11IGG7','M11IGG6','M11IGG5','M11IGG4','M11IGG3','M11IGG2','M11IGG10','M11IGG1','M11IGF2','M11IGF1','M11IGE2','M11IGE1','M11IGD2','M11IGD1','M11IGC2','M11IGC1','M11IGB2','M11IGB1','M11IGA2','M11IGA1')
UNION
SELECT  10 AS ORD,
'10º PERIODO - 2023/2' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 110
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M10IGG3','M10IGG2','M10IGG1','M10IGF3','M10IGF2','M10IGF1','M10IGE3','M10IGE2','M10IGE1','M10IGD3','M10IGD2','M10IGD1','M10IGC3','M10IGC2','M10IGC1','M10IGB3','M10IGB2','M10IGB1','M10IGA3','M10IGA2','M10IGA1','M10GDA','M10DDA','M10BDA','M10ADA')
UNION
SELECT  11 AS ORD,
'11º PERIODO - 2023/1' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
WHERE SMATRICULA.IDPERLET = 102
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M9IGG3','M9IGG2','M9IGG1','M9IGF3','M9IGF2','M9IGF1','M9IGE3','M9IGE2','M9IGE1','M9IGD3','M9IGD2','M9IGD1','M9IGC3','M9IGC2','M9IGC1','M9IGB3','M9IGB2','M9IGB1','M9IGA3','M9IGA2','M9IGA1','M9GDA','M9DDA','M9BDA')
UNION
SELECT 12 AS ORD,
'12º PERIODO - 2023/2' AS 'PERIODO', 
COUNT( DISTINCT SMATRICULA.RA) AS 'MATRICULADOS'
    FROM SMATRICULA
JOIN STURMADISC
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
    AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SMATRICPL
    ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SMATRICPL.RA = SMATRICULA.RA
        AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
JOIN SSTATUS
    ON SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
    AND SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
WHERE SMATRICULA.IDPERLET = 110
    AND SHABILITACAOFILIAL.CODCURSO = '03'
    AND SMATRICPL.CODSTATUS NOT IN(28, 10)
AND STURMADISC.CODTURMA IN ('M12IGG9','M12IGG8','M12IGG7','M12IGG6','M12IGG5','M12IGG4','M12IGG3','M12IGG2','M12IGG10','M12IGG1','M12IGF2','M12IGF1','M12IGE2','M12IGE1','M12IGD2','M12IGD1','M12IGC2','M12IGC1','M12IGB2','M12IGB1','M12IGA2','M12IGA1')
ORDER BY 1