SELECT PFDEPEND.NOME                                                   AS 'NOME_DEPENDENTE',
       CONVERT(VARCHAR, PFDEPEND.DTNASCIMENTO, 103)                    AS 'DT_NASCIMENTO'
FROM   PFDEPEND
       JOIN PFUNC
         ON PFDEPEND.CHAPA = PFUNC.CHAPA
            AND PFDEPEND.CODCOLIGADA = PFUNC.CODCOLIGADA
       JOIN PSECAO
         ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
            AND PSECAO.CODIGO = PFUNC.CODSECAO
WHERE  PFUNC.CODSITUACAO = 'A'
       AND PSECAO.CODFILIAL = 1
       AND PFUNC.CODCOLIGADA = 1
       AND PFDEPEND.GRAUPARENTESCO != '6'
       AND PFDEPEND.GRAUPARENTESCO != '7'
       AND PFUNC.CHAPA = '112052'
GROUP  BY PFUNC.CHAPA,
          PFUNC.NOME,
          PSECAO.DESCRICAO,
          PFDEPEND.GRAUPARENTESCO,
          PFDEPEND.NRODEPEND,
          PFDEPEND.NOME,
          PFDEPEND.DTNASCIMENTO
ORDER  BY PFUNC.NOME,
          PFUNC.CHAPA,
          PFDEPEND.NRODEPEND 
