SELECT Cast(BMEMO.VALMEMO AS VARCHAR(MAX))  AS 'RESPOSTA',
       SPROFESSOR.CODPROF                   AS 'CODIGO_PROFESSOR',
       PPESSOA.NOME                         AS 'NOME_PROFESSOR',
       Cast(BQUESTAO.TEXTO AS VARCHAR(MAX)) AS 'QUESTAO'
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN SPROFESSOR (NOLOCK)
         ON SPROFESSOR.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND SPROFESSOR.CODPROF = SOBJETOAVALIADO.CODPROF
       JOIN PPESSOA (NOLOCK)
         ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
       JOIN SPROFESSORFILIAL (NOLOCK)
         ON SPROFESSORFILIAL.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
            AND SPROFESSORFILIAL.CODPROF = SPROFESSOR.CODPROF
       JOIN STURMADISC (NOLOCK)
         ON STURMADISC.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND STURMADISC.IDTURMADISC = SOBJETOAVALIADO.IDTURMADISC
       JOIN SPLETIVO (NOLOCK)
         ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
            AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
       JOIN STURMA(NOLOCK)
         ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
            AND STURMA.IDPERLET = STURMADISC.IDPERLET
            AND STURMA.CODFILIAL = STURMADISC.CODFILIAL
            AND STURMA.CODTURMA = STURMADISC.CODTURMA
       JOIN BMEMO (NOLOCK)
         ON BMEMO.ID = BHISTRESPPROVA.IDMEMORESPABERTA
WHERE  STURMADISC.CODTURMA = :TURMA2
       AND SPLETIVO.CODPERLET = :PERIODO2
       AND SPROFESSORFILIAL.CODFILIAL = :FILIALPROFESSOR2
       AND BHISTORICO.CODPROVA = :CODIGOPROVA1
       AND Cast(BMEMO.VALMEMO AS VARCHAR(MAX)) != ''
GROUP  BY SPROFESSOR.CODPROF,
          BMEMO.ID,
          Cast(BMEMO.VALMEMO AS VARCHAR(MAX)),
          Cast(BQUESTAO.TEXTO AS VARCHAR(MAX)),
          SPROFESSOR.CODPROF,
          PPESSOA.NOME 
