
    SELECT DISTINCT
        (((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND SHISTORICO.[STATUS] = 'Aprovado') /* +
	 (SELECT ISNULL(SUM(CH),0) FROM SHISTDISCOPTELETIVAS (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado')*/)) AS 'CARGA_DISCIPLINAS',
        SGRADE.CARGAHORARIA AS 'CARGA_GRADE',
        (((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND SHISTORICO.[STATUS] = 'Aprovado') )) * 100 / 
	    SGRADE.CARGAHORARIA AS '%',
        SMATRICPL.RA AS 'MATRICULA',
        PPESSOA.NOME AS 'ALUNO',
        '2311101' AS CO_PROJETO
	, 'E' AS TP_ORIGEM
	, CASE
		WHEN SHABILITACAOFILIAL.CODFILIAL = '1' THEN '2579'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '2' AND SHABILITACAOFILIAL.CODCURSO != '01' THEN '22194'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '2' AND SHABILITACAOFILIAL.CODCURSO = '01' THEN '24404'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '3' AND SHABILITACAOFILIAL.CODCURSO != '01' THEN '22197'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '3' AND SHABILITACAOFILIAL.CODCURSO = '01' THEN '24403'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '5' THEN '24471'		
	END AS CO_IES
	, CASE
                  WHEN SHABILITACAOFILIAL.CODCURSO = '01' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '54938'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '01' AND SHABILITACAOFILIAL.CODFILIAL = '2' THEN '1478070'
				  WHEN SHABILITACAOFILIAL.CODCURSO = '01' AND SHABILITACAOFILIAL.CODFILIAL = '3' THEN '1478068'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '90059'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '2' THEN '1399617'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '3' THEN '1408507'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '5' THEN '1484883'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '05' THEN '97089'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '06' THEN '97085'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '07' THEN '97087'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '08' THEN '405178'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '09' THEN '105178'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '10' THEN '1187878'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '11' THEN '1187880'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '12' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '1187877'
				  WHEN SHABILITACAOFILIAL.CODCURSO = '12' AND SHABILITACAOFILIAL.CODFILIAL = '2' THEN '1478339'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '13' THEN '1205398'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '14' THEN '1285224'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '15' THEN '1467961'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '16' THEN '1467971'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '17' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '1466185'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '17' AND SHABILITACAOFILIAL.CODFILIAL = '3' THEN '1477104'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E01' THEN '1307526'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E02' THEN '1457056'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E03' THEN '1457052'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E04' THEN '1457051'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E05' THEN '1457050'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E06' THEN '1457057'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E07' THEN '1457055'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E08' THEN '1308809'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E09' THEN '1486634'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E10' THEN '1486633'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E11' THEN '1486636'
                END AS CO_CURSO
	, PPESSOA.CPF as NU_CPF
	, SPESSOA.ANOULTIMAINST AS NU_ANO_FIM_ENSINO_MEDIO
	, CASE
		WHEN SHABILITACAOFILIAL.CODTURNO = 1 THEN '1'
		WHEN SHABILITACAOFILIAL.CODTURNO = 2 THEN '2'
		WHEN SHABILITACAOFILIAL.CODTURNO = 5 THEN '3'
		WHEN SHABILITACAOFILIAL.CODTURNO = 3 THEN '4'
		WHEN SHABILITACAOFILIAL.CODTURNO = 16 THEN '4'
	END AS CO_TURNO_GRADUACAO
	, CAST((((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL) + 
	(SELECT ISNULL(SUM(CH),0)
        FROM SHISTDISCOPTELETIVAS (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado')) * 100 / 
	(SGRADE.CARGAHORARIA + (SELECT ISNULL(SUM(CH),0)
        FROM SHISTDISCOPTELETIVAS (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado'))) AS DECIMAL(6,1)) AS NU_PERCENTUAL_INTEGRALIZACAO
	, '2023' AS NU_ANO_FORMATURA
	, '1' AS NU_SEMESTRE_FORMATURA
	, YEAR(SHABILITACAOALUNO.DTINGRESSO) AS NU_ANO_INICIO_GRADUACAO
	, 0 AS IN_MUNICIPIO_POLO_EXTERIOR
	, CASE
	WHEN SHABILITACAOFILIAL.CODFILIAL = 1 AND SHABILITACAOFILIAL.CODTIPOCURSO = 2 THEN '3147006'
	ELSE ''
	END AS CO_MUNICIPIO_POLO
    FROM
        SMATRICPL (NOLOCK)
        JOIN SHABILITACAOFILIAL (NOLOCK)
        ON  SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
        JOIN SCURSO (NOLOCK)
        ON  SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
        JOIN SHABILITACAOALUNO (NOLOCK)
        ON  SHABILITACAOALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
            AND SHABILITACAOALUNO.RA = SMATRICPL.RA
            AND SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
        JOIN SHISTHABILITACAOALUNO (NOLOCK)
        ON  SHISTHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
            AND SHISTHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
            AND SHISTHABILITACAOALUNO.RA = SHABILITACAOALUNO.RA
        JOIN SHISTORICO (NOLOCK)
        ON  SHISTORICO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SHISTORICO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
        JOIN SALUNO (NOLOCK)
        ON  SALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SALUNO.RA = SMATRICPL.RA
            AND SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
            AND SALUNO.RA = SHABILITACAOALUNO.RA
        JOIN PPESSOA (NOLOCK)
        ON  PPESSOA.CODIGO = SALUNO.CODPESSOA
        JOIN SGRADE (NOLOCK)
        ON  SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
            AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
            AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
        JOIN SSTATUS (NOLOCK)
        ON  SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
        JOIN SPESSOA (NOLOCK)
        ON PPESSOA.CODIGO = SPESSOA.CODIGO
        JOIN STURNO (NOLOCK)
        ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
    WHERE
	SCURSO.CODCURSO = '03'
        AND SMATRICPL.IDPERLET = 110
        AND SHABILITACAOALUNO.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 110 /*AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SMATRICPL.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 110 /*AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SHISTHABILITACAOALUNO.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 110/* AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SHISTORICO.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 110/* AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SHABILITACAOALUNO.DTCOLACAOGRAU IS NULL
        --AND SMATRICPL.RA = '19-1-14686'
        /*AND (((SELECT SUM(CH) FROM SHISTORICO (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL) +
	 (SELECT ISNULL(SUM(CH),0) FROM SHISTDISCOPTELETIVAS (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado'))) * 100 / 
	 (SGRADE.CARGAHORARIA + (SELECT ISNULL(SUM(CH),0) FROM SHISTDISCOPTELETIVAS (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado')) >= 75.00*/
       AND ((((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND SHISTORICO.[STATUS] = 'Aprovado') )) * 100 / 
	    SGRADE.CARGAHORARIA) >= 75
        AND SMATRICPL.RA NOT LIKE '21-%'
        AND SMATRICPL.RA NOT LIKE '22-%'
        AND SMATRICPL.RA NOT LIKE '23-%'
UNION



    SELECT DISTINCT
        (((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND SHISTORICO.[STATUS] = 'Aprovado') /* +
	 (SELECT ISNULL(SUM(CH),0) FROM SHISTDISCOPTELETIVAS (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado')*/)) AS 'CARGA_DISCIPLINAS',
        SGRADE.CARGAHORARIA AS 'CARGA_GRADE',
        (((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND SHISTORICO.[STATUS] = 'Aprovado') )) * 100 / 
	    SGRADE.CARGAHORARIA AS '%',
        SMATRICPL.RA AS 'MATRICULA',
        PPESSOA.NOME AS 'ALUNO',
        '2311101' AS CO_PROJETO
	, 'E' AS TP_ORIGEM
	, CASE
		WHEN SHABILITACAOFILIAL.CODFILIAL = '1' THEN '2579'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '2' AND SHABILITACAOFILIAL.CODCURSO != '01' THEN '22194'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '2' AND SHABILITACAOFILIAL.CODCURSO = '01' THEN '24404'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '3' AND SHABILITACAOFILIAL.CODCURSO != '01' THEN '22197'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '3' AND SHABILITACAOFILIAL.CODCURSO = '01' THEN '24403'
		WHEN SHABILITACAOFILIAL.CODFILIAL = '5' THEN '24471'		
	END AS CO_IES
	, CASE
                  WHEN SHABILITACAOFILIAL.CODCURSO = '01' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '54938'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '01' AND SHABILITACAOFILIAL.CODFILIAL = '2' THEN '1478070'
				  WHEN SHABILITACAOFILIAL.CODCURSO = '01' AND SHABILITACAOFILIAL.CODFILIAL = '3' THEN '1478068'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '90059'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '2' THEN '1399617'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '3' THEN '1408507'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '03' AND SHABILITACAOFILIAL.CODFILIAL = '5' THEN '1484883'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '05' THEN '97089'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '06' THEN '97085'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '07' THEN '97087'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '08' THEN '405178'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '09' THEN '105178'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '10' THEN '1187878'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '11' THEN '1187880'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '12' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '1187877'
				  WHEN SHABILITACAOFILIAL.CODCURSO = '12' AND SHABILITACAOFILIAL.CODFILIAL = '2' THEN '1478339'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '13' THEN '1205398'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '14' THEN '1285224'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '15' THEN '1467961'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '16' THEN '1467971'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '17' AND SHABILITACAOFILIAL.CODFILIAL = '1' THEN '1466185'
                  WHEN SHABILITACAOFILIAL.CODCURSO = '17' AND SHABILITACAOFILIAL.CODFILIAL = '3' THEN '1477104'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E01' THEN '1307526'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E02' THEN '1457056'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E03' THEN '1457052'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E04' THEN '1457051'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E05' THEN '1457050'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E06' THEN '1457057'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E07' THEN '1457055'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E08' THEN '1308809'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E09' THEN '1486634'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E10' THEN '1486633'
                  WHEN SHABILITACAOFILIAL.CODCURSO = 'E11' THEN '1486636'
                END AS CO_CURSO
	, PPESSOA.CPF as NU_CPF
	, SPESSOA.ANOULTIMAINST AS NU_ANO_FIM_ENSINO_MEDIO
	, CASE
		WHEN SHABILITACAOFILIAL.CODTURNO = 1 THEN '1'
		WHEN SHABILITACAOFILIAL.CODTURNO = 2 THEN '2'
		WHEN SHABILITACAOFILIAL.CODTURNO = 5 THEN '3'
		WHEN SHABILITACAOFILIAL.CODTURNO = 3 THEN '4'
		WHEN SHABILITACAOFILIAL.CODTURNO = 16 THEN '4'
	END AS CO_TURNO_GRADUACAO
	, (((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL) + (SELECT ISNULL(SUM(CH),0)
        FROM SHISTDISCOPTELETIVAS (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado')))
	, '2023' AS NU_ANO_FORMATURA
	, '2' AS NU_SEMESTRE_FORMATURA
	, YEAR(SHABILITACAOALUNO.DTINGRESSO) AS NU_ANO_INICIO_GRADUACAO
	, 0 AS IN_MUNICIPIO_POLO_EXTERIOR
	, CASE
	WHEN SHABILITACAOFILIAL.CODFILIAL = 1 AND SHABILITACAOFILIAL.CODTIPOCURSO = 2 THEN '3147006'
	ELSE ''
	END AS CO_MUNICIPIO_POLO
    FROM
        SMATRICPL (NOLOCK)
        JOIN SHABILITACAOFILIAL (NOLOCK)
        ON  SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
        JOIN SCURSO (NOLOCK)
        ON  SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
        JOIN SHABILITACAOALUNO (NOLOCK)
        ON  SHABILITACAOALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
            AND SHABILITACAOALUNO.RA = SMATRICPL.RA
            AND SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
        JOIN SHISTHABILITACAOALUNO (NOLOCK)
        ON  SHISTHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
            AND SHISTHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
            AND SHISTHABILITACAOALUNO.RA = SHABILITACAOALUNO.RA
        JOIN SHISTORICO (NOLOCK)
        ON  SHISTORICO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SHISTORICO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
        JOIN SALUNO (NOLOCK)
        ON  SALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SALUNO.RA = SMATRICPL.RA
            AND SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
            AND SALUNO.RA = SHABILITACAOALUNO.RA
        JOIN PPESSOA (NOLOCK)
        ON  PPESSOA.CODIGO = SALUNO.CODPESSOA
        JOIN SGRADE (NOLOCK)
        ON  SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
            AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
            AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
        JOIN SSTATUS (NOLOCK)
        ON  SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
        JOIN SPESSOA (NOLOCK)
        ON PPESSOA.CODIGO = SPESSOA.CODIGO
        JOIN STURNO (NOLOCK)
        ON STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
            AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
    WHERE
	SCURSO.CODCURSO = '03'
        AND SMATRICPL.IDPERLET = 102
        AND SHABILITACAOALUNO.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 102 /*AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SMATRICPL.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 102 /*AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SHISTHABILITACAOALUNO.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 102/* AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SHISTORICO.RA IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 102/* AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SHABILITACAOALUNO.DTCOLACAOGRAU IS NULL
        --AND SMATRICPL.RA = '19-1-14686'
        /*AND (((SELECT SUM(CH) FROM SHISTORICO (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL) +
	 (SELECT ISNULL(SUM(CH),0) FROM SHISTDISCOPTELETIVAS (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado'))) * 100 / 
	 (SGRADE.CARGAHORARIA + (SELECT ISNULL(SUM(CH),0) FROM SHISTDISCOPTELETIVAS (NOLOCK) WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND STATUS = 'Aprovado')) >= 75.00*/
        AND ((((SELECT SUM(CH)
        FROM SHISTORICO (NOLOCK)
        WHERE RA = SMATRICPL.RA AND IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL AND SHISTORICO.[STATUS] = 'Aprovado') )) * 100 / 
	    SGRADE.CARGAHORARIA) >= 75


        AND SMATRICPL.RA NOT IN (SELECT DISTINCT RA
        FROM SMATRICPL (NOLOCK)
        WHERE SMATRICPL.IDPERLET = 110 /*AND SMATRICPL.CODTURMA LIKE 'ADM7%'*/)
        AND SMATRICPL.RA NOT LIKE '21-%'
        AND SMATRICPL.RA NOT LIKE '22-%'
        AND SMATRICPL.RA NOT LIKE '23-%'
ORDER BY 3 DESC