SELECT LPUBLIC.CODIGO AS 'CODIDO_PUBLICACAO',
LPUBLIC.TITULO AS 'TITULO_PUBLICACAO', 
convert(varchar, LEMPRESTIMOS.DTHRDEVPREVISTA, 103) AS 'DATA_PREVISTA', 
convert(varchar, LEMPRESTIMOS.DTHRDEVEFETIVA, 103) AS 'DATA_DEVOLUCAO', 
CONCAT( 'R$ ', LEMPRESTIMOS.VALORMULTA) AS 'VALOR_MULTA', 
SALUNO.RA AS 'MATRICULA',
PPESSOA.NOME AS 'NOME_ALUNO'

FROM LEMPRESTIMOS
    JOIN LPUBLIC
    ON LPUBLIC.CODCOLIGADA = LEMPRESTIMOS.CODCOLIGADA
        AND LPUBLIC.CODIGO = LEMPRESTIMOS.CODPUBLIC
    JOIN LUSUARIO
    ON LUSUARIO.CODCOLIGADA = LEMPRESTIMOS.CODCOLIGADA
        AND LUSUARIO.CODIGO = LEMPRESTIMOS.CODCLIENTE
    JOIN PPESSOA
    ON PPESSOA.CODIGO = LUSUARIO.CODPESSOA
    JOIN SALUNO
    ON SALUNO.CODPESSOA = LUSUARIO.CODPESSOA

WHERE LEMPRESTIMOS.DTHRDEVEFETIVA <= '2023/12/31'
    AND LEMPRESTIMOS.DTHRDEVEFETIVA >= '2022/01/01'
    AND LEMPRESTIMOS.VALORMULTA != '0.00'
    AND LEMPRESTIMOS.CODFILIAL = 01
ORDER BY 7
