SELECT PFUNC.CHAPA AS 'MATRICULA',
    PPESSOA.NOME AS 'NOME_FUNCIONARIO',
    PSECAO.DESCRICAO AS 'CODSECAO',
    PFUNCAO.NOME AS 'CODFUNCAO',
    CASE
        WHEN convert(varchar, PPESSOA.DTVENCHABILIT, 103) IS NULL THEN '-'
        ELSE convert(varchar, PPESSOA.DTVENCHABILIT, 103)
    END AS 'VENCIMENTO_HABILITACAO',
    CASE
        WHEN  (SELECT TOP 1
       US.CODUSUARIOREDE + '@bevap.com.br'
    FROM PSUBSTCHEFE P
    JOIN PFUNC PF
        ON PF.CODCOLIGADA = P.CODCOLSUBST
        AND PF.CHAPA = P.CHAPASUBST
    JOIN PPESSOA PP
        ON PP.CODIGO = PF.CODPESSOA
    JOIN GUSUARIO US
    ON US.CODUSUARIO = PP.CODUSUARIO
    WHERE P.CODSECAO = PSECAO.CODIGO
    AND P.MASTER = 1
    ORDER BY P.DATAINICIO DESC) IS NULL THEN '-'
    ELSE (SELECT TOP 1
       US.CODUSUARIOREDE + '@bevap.com.br'
    FROM PSUBSTCHEFE P
    JOIN PFUNC PF
        ON PF.CODCOLIGADA = P.CODCOLSUBST
        AND PF.CHAPA = P.CHAPASUBST
    JOIN PPESSOA PP
        ON PP.CODIGO = PF.CODPESSOA
    JOIN GUSUARIO US
    ON US.CODUSUARIO = PP.CODUSUARIO
    WHERE P.CODSECAO = PSECAO.CODIGO
        AND P.MASTER = 1
    ORDER BY P.DATAINICIO DESC) 
    END AS 'EMAIL_GESTOR'
FROM PFUNC
    JOIN PPESSOA
    ON PPESSOA.CODIGO = PFUNC.CODPESSOA
    JOIN PSECAO
    ON PSECAO.CODIGO = PFUNC.CODSECAO
        AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
    JOIN PFUNCAO
        ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
        AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
WHERE PFUNC.CODSITUACAO IN('A' , 'F')
AND PFUNC.CODCOLIGADA = 1
ORDER BY 2
