SELECT (SELECT Cast(BOPCAO.TEXTO AS VARCHAR(MAX))
        FROM   BQUESTAO (NOLOCK)
               JOIN BOPCAO(NOLOCK)
                 ON BOPCAO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
                    AND BOPCAO.CODAREA = BQUESTAO.CODAREA
                    AND BOPCAO.CODMATERIA = BQUESTAO.CODMATERIA
                    AND BOPCAO.CODQUESTAO = BQUESTAO.CODQUESTAO
        WHERE  BOPCAO.CODQUESTAO = 02
               AND BOPCAO.CODAREA = 33
               AND BOPCAO.CODOPCAO LIKE 'A') AS 'ALTERNATIVA',
       Count(DISTINCT BHISTRESPPROVA.ID)     AS VALOR
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
WHERE  BHISTORICO.CODPROVA = 42
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND BHISTORICO.CODQUESTAO = :CODQUESTAO1
       AND BHISTRESPPROVA.CODRESPOSTA LIKE 'A'
GROUP  BY BHISTRESPPROVA.CODRESPOSTA
UNION
SELECT (SELECT Cast(BOPCAO.TEXTO AS VARCHAR(MAX))
        FROM   BQUESTAO (NOLOCK)
               JOIN BOPCAO(NOLOCK)
                 ON BOPCAO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
                    AND BOPCAO.CODAREA = BQUESTAO.CODAREA
                    AND BOPCAO.CODMATERIA = BQUESTAO.CODMATERIA
                    AND BOPCAO.CODQUESTAO = BQUESTAO.CODQUESTAO
        WHERE  BOPCAO.CODQUESTAO = 02
               AND BOPCAO.CODAREA = 33
               AND BOPCAO.CODOPCAO LIKE 'B') AS 'ALTERNATIVA',
       Count(DISTINCT BHISTRESPPROVA.ID)     AS VALOR
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
WHERE  BHISTORICO.CODPROVA = 42
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND BHISTORICO.CODQUESTAO = :CODQUESTAO
       AND BHISTRESPPROVA.CODRESPOSTA LIKE 'B'
GROUP  BY BHISTRESPPROVA.CODRESPOSTA

UNION
SELECT (SELECT Cast(BOPCAO.TEXTO AS VARCHAR(MAX))
        FROM   BQUESTAO (NOLOCK)
               JOIN BOPCAO(NOLOCK)
                 ON BOPCAO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
                    AND BOPCAO.CODAREA = BQUESTAO.CODAREA
                    AND BOPCAO.CODMATERIA = BQUESTAO.CODMATERIA
                    AND BOPCAO.CODQUESTAO = BQUESTAO.CODQUESTAO
        WHERE  BOPCAO.CODQUESTAO = 02
               AND BOPCAO.CODAREA = 33
               AND BOPCAO.CODOPCAO LIKE 'C') AS 'ALTERNATIVA',
       Count(DISTINCT BHISTRESPPROVA.ID)     AS VALOR
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
WHERE  BHISTORICO.CODPROVA = 42
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND BHISTORICO.CODQUESTAO = :CODQUESTAO1
       AND BHISTRESPPROVA.CODRESPOSTA LIKE 'C'
GROUP  BY BHISTRESPPROVA.CODRESPOSTA

UNION
SELECT (SELECT Cast(BOPCAO.TEXTO AS VARCHAR(MAX))
        FROM   BQUESTAO (NOLOCK)
               JOIN BOPCAO(NOLOCK)
                 ON BOPCAO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
                    AND BOPCAO.CODAREA = BQUESTAO.CODAREA
                    AND BOPCAO.CODMATERIA = BQUESTAO.CODMATERIA
                    AND BOPCAO.CODQUESTAO = BQUESTAO.CODQUESTAO
        WHERE  BOPCAO.CODQUESTAO = 02
               AND BOPCAO.CODAREA = 33
               AND BOPCAO.CODOPCAO LIKE 'D') AS 'ALTERNATIVA',
       Count(DISTINCT BHISTRESPPROVA.ID)     AS VALOR
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
WHERE  BHISTORICO.CODPROVA = 42
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND BHISTORICO.CODQUESTAO = :CODQUESTAO1
       AND BHISTRESPPROVA.CODRESPOSTA LIKE 'D'
GROUP  BY BHISTRESPPROVA.CODRESPOSTA

UNION
SELECT (SELECT Cast(BOPCAO.TEXTO AS VARCHAR(MAX))
        FROM   BQUESTAO (NOLOCK)
               JOIN BOPCAO(NOLOCK)
                 ON BOPCAO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
                    AND BOPCAO.CODAREA = BQUESTAO.CODAREA
                    AND BOPCAO.CODMATERIA = BQUESTAO.CODMATERIA
                    AND BOPCAO.CODQUESTAO = BQUESTAO.CODQUESTAO
        WHERE  BOPCAO.CODQUESTAO = 02
               AND BOPCAO.CODAREA = 33
               AND BOPCAO.CODOPCAO LIKE 'E') AS 'ALTERNATIVA',
       Count(DISTINCT BHISTRESPPROVA.ID)     AS VALOR
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
WHERE  BHISTORICO.CODPROVA = 42
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND BHISTORICO.CODQUESTAO = :CODQUESTAO1
       AND BHISTRESPPROVA.CODRESPOSTA LIKE 'E'
GROUP  BY BHISTRESPPROVA.CODRESPOSTA

UNION
SELECT (SELECT Cast(BOPCAO.TEXTO AS VARCHAR(MAX))
        FROM   BQUESTAO (NOLOCK)
               JOIN BOPCAO(NOLOCK)
                 ON BOPCAO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
                    AND BOPCAO.CODAREA = BQUESTAO.CODAREA
                    AND BOPCAO.CODMATERIA = BQUESTAO.CODMATERIA
                    AND BOPCAO.CODQUESTAO = BQUESTAO.CODQUESTAO
        WHERE  BOPCAO.CODQUESTAO = 02
               AND BOPCAO.CODAREA = 33
               AND BOPCAO.CODOPCAO LIKE 'F') AS 'ALTERNATIVA',
       Count(DISTINCT BHISTRESPPROVA.ID)     AS VALOR
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
WHERE  BHISTORICO.CODPROVA = 42
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND BHISTORICO.CODQUESTAO = :CODQUESTAO1
       AND BHISTRESPPROVA.CODRESPOSTA LIKE 'F'
GROUP  BY BHISTRESPPROVA.CODRESPOSTA 
