SELECT DISTINCT SMATRICPL.RA                                                                                                                                                                     AS 'MATRICULA',
    PPESSOA.NOME                                                                                                                                                                     AS 'ALUNO',
    ( (SELECT Count(1)
    FROM SDISCGRADE S
    WHERE  S.CODCOLIGADA = SGRADE.CODCOLIGADA
        AND S.CODGRADE = SGRADE.CODGRADE
        AND S.CODCURSO = SGRADE.CODCURSO)
                  + (SELECT Count(1)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) )                                                                                                                           AS 'QTD DISCIPLINAS MATRIZ',
    CONVERT(INT, ( SGRADE.CARGAHORARIA
                               + (SELECT ISNULL(Sum(CH), 0)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) ))                                                                                                             AS 'CH MATRIZ',
    ( CONVERT(INT, ( SGRADE.CARGAHORARIA
                               + (SELECT ISNULL(Sum(CH), 0)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) ))) - (SELECT Sum(CH)
    FROM SHISTDISCPENDENTES S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL)                                                                                                AS 'CH PORC. APROVADO',
    ((SELECT Count(1)
    FROM SDISCGRADE S
    WHERE  S.CODCOLIGADA = SGRADE.CODCOLIGADA
        AND S.CODGRADE = SGRADE.CODGRADE
        AND S.CODCURSO = SGRADE.CODCURSO)
                + (SELECT Count(1)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) - (SELECT Count(1)
    FROM SHISTDISCPENDENTES S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL))                                                                                                                            AS 'QTD DISC APROVADO',

    (((SELECT Count(1)
    FROM SDISCGRADE S
    WHERE  S.CODCOLIGADA = SGRADE.CODCOLIGADA
        AND S.CODGRADE = SGRADE.CODGRADE
        AND S.CODCURSO = SGRADE.CODCURSO)
                + (SELECT Count(1)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) - (SELECT Count(1)
    FROM SHISTDISCPENDENTES S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL)) * 100) /  ( (SELECT Count(1)
    FROM SDISCGRADE S
    WHERE  S.CODCOLIGADA = SGRADE.CODCOLIGADA
        AND S.CODGRADE = SGRADE.CODGRADE
        AND S.CODCURSO = SGRADE.CODCURSO)
                  + (SELECT Count(1)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) )  
                 AS '% DISC APROVADA',
    Cast(( ( (SELECT Sum(NOTA)
    FROM SHISTDISCCONCLUIDAS S (NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND STATUS != 'Dispensado')
                         + (SELECT ISNULL(Sum(NOTA), 0)
    FROM SHISTDISCOPTELETIVAS S (NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) ) / ( (SELECT Count(1)
    FROM SHISTDISCCONCLUIDAS S (NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND S.STATUS != 'Dispensado')
                                                                                  + (SELECT Count(1)
    FROM SHISTDISCOPTELETIVAS S (NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) ) ) AS DECIMAL(10, 1))                                      AS 'MEDIA NOTAS APROVADO',
    ''                                                                                                                                                                               AS 'REG',
    ''                                                                                                                                                                               AS 'DEP',
    ((SELECT Count(1)
    FROM SHISTDISCPENDENTES S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL))                                                   AS 'QTD DISC FALTANTES'
FROM SMATRICPL (NOLOCK)
    JOIN SHABILITACAOFILIAL (NOLOCK)
    ON SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
    JOIN SCURSO (NOLOCK)
    ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
    JOIN SHABILITACAOALUNO (NOLOCK)
    ON SHABILITACAOALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
        AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
        AND SHABILITACAOALUNO.RA = SMATRICPL.RA
        AND SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
    JOIN SHISTHABILITACAOALUNO (NOLOCK)
    ON SHISTHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
        AND SHISTHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND SHISTHABILITACAOALUNO.RA = SHABILITACAOALUNO.RA
    JOIN SHISTDISCCONCLUIDAS (NOLOCK)
    ON SHISTDISCCONCLUIDAS.CODCOLIGADA = SHISTHABILITACAOALUNO.CODCOLIGADA
        AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = SHISTHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND SHISTDISCCONCLUIDAS.RA = SHISTHABILITACAOALUNO.RA
    JOIN SALUNO (NOLOCK)
    ON SALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
        AND SALUNO.RA = SMATRICPL.RA
        AND SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
        AND SALUNO.RA = SHABILITACAOALUNO.RA
    JOIN PPESSOA (NOLOCK)
    ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    JOIN SGRADE (NOLOCK)
    ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
        AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
        AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
    JOIN SSTATUS (NOLOCK)
    ON SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
        AND SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
WHERE  SCURSO.CODCURSO = 'E09'
    AND SMATRICPL.IDPERLET = 103
    -- AND SMATRICPL.PERIODO >= 11
    AND SHABILITACAOALUNO.DTCOLACAOGRAU IS NULL
    AND (((SELECT Count(1)
    FROM SDISCGRADE S
    WHERE  S.CODCOLIGADA = SGRADE.CODCOLIGADA
        AND S.CODGRADE = SGRADE.CODGRADE
        AND S.CODCURSO = SGRADE.CODCURSO)
                + (SELECT Count(1)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) - (SELECT Count(1)
    FROM SHISTDISCPENDENTES S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL)) * 100) /  ( (SELECT Count(1)
    FROM SDISCGRADE S
    WHERE  S.CODCOLIGADA = SGRADE.CODCOLIGADA
        AND S.CODGRADE = SGRADE.CODGRADE
        AND S.CODCURSO = SGRADE.CODCURSO)
                  + (SELECT Count(1)
    FROM SHISTDISCOPTELETIVAS S(NOLOCK)
    WHERE  S.RA = SMATRICPL.RA
        AND S.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
        AND ( S.STATUS = 'Aprovado'
        OR S.STATUS = 'Dispensado'
        OR S.STATUS = 'Exame Especial' )) ) >= 80
ORDER  BY 8 DESC 
