SET LANGUAGE PORTUGUESE;

SELECT DISTINCT SALUNO.RA                               AS 'MATRICULA',
    PPESSOA.NOME                            AS 'ALUNO',
    (SELECT NOME
    FROM PPESSOA
    WHERE  CODIGO = SPROFESSOR.CODPESSOA)  AS 'PROFESSOR',
    SDISCIPLINA.NOME                        AS 'DISCIPLINA',
    CONVERT(INT, SDISCIPLINA.CH)            AS 'CH',
    SCURSO.NOME                             AS 'CURSO',
    Month(SPLANOAULA.DATA)                  AS 'MES',
    SMATRICULA.CODSUBTURMA,
    SMATRICULA.IDTURMADISC,
    Upper(Datename(MONTH, SPLANOAULA.DATA)) AS 'MESES',
    SPLETIVO.CODPERLET                      AS 'PERIODOLETIVO',
    CASE
                  WHEN Month(SFREQUENCIA.DATA) = 01 THEN 1
                  WHEN Month(SFREQUENCIA.DATA) = 02 THEN 2
                  WHEN Month(SFREQUENCIA.DATA) = 03 THEN 3
                  WHEN Month(SFREQUENCIA.DATA) = 04 THEN 4
                  WHEN Month(SFREQUENCIA.DATA) = 05 THEN 5
                  WHEN Month(SFREQUENCIA.DATA) = 06 THEN 6
                  WHEN Month(SFREQUENCIA.DATA) = 07 THEN 7
                  WHEN Month(SFREQUENCIA.DATA) = 08 THEN 8
                  WHEN Month(SFREQUENCIA.DATA) = 09 THEN 9
                  WHEN Month(SFREQUENCIA.DATA) = 10 THEN 10
                  WHEN Month(SFREQUENCIA.DATA) = 11 THEN 11
                  WHEN Month(SFREQUENCIA.DATA) = 12 THEN 12
                END                                                                              AS 'ORDENAR',
    STURMADISC.CODTURMA
FROM SMATRICULA (NOLOCK)
    JOIN SALUNO (NOLOCK)
    ON SALUNO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SALUNO.RA = SMATRICULA.RA
    JOIN PPESSOA (NOLOCK)
    ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    JOIN STURMADISC (NOLOCK)
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    JOIN SPROFESSORTURMA (NOLOCK)
    ON STURMADISC.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
        AND STURMADISC.IDTURMADISC = SPROFESSORTURMA.IDTURMADISC
    JOIN SPROFESSOR (NOLOCK)
    ON SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
        AND SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
    JOIN SDISCIPLINA (NOLOCK)
    ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
    JOIN SHABILITACAOFILIAL (NOLOCK)
    ON SHABILITACAOFILIAL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
        AND SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
    JOIN SCURSO (NOLOCK)
    ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
    JOIN SPLANOAULA (NOLOCK)
    ON SPLANOAULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SPLANOAULA.IDTURMADISC = STURMADISC.IDTURMADISC
    JOIN SPLETIVO (NOLOCK)
    ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
    JOIN SFREQUENCIA
    ON SMATRICULA.CODCOLIGADA = SFREQUENCIA.CODCOLIGADA
        AND SMATRICULA.IDTURMADISC = SFREQUENCIA.IDTURMADISC
        AND SMATRICULA.RA = SFREQUENCIA.RA
WHERE  SMATRICULA.RA = '22-1-18177'
    AND SPLANOAULA.DATA <= Getdate()
    AND SPROFESSORTURMA.TIPOPROF = 'T' 
      AND SMATRICULA.IDTURMADISC = 24152
     
       
