SELECT BHISTORICO.CODQUESTAO                'CODIGO_QUESTAO',
       Cast(BQUESTAO.TEXTO AS VARCHAR(MAX)) AS 'QUESTAO',
       Count(CASE
               WHEN BHISTRESPPROVA.CODRESPOSTA = 'A' THEN 1
             END) * 5                       AS 'A',
       Count(CASE
               WHEN BHISTRESPPROVA.CODRESPOSTA = 'B' THEN 1
             END) * 4                       AS 'B',
       Count(CASE
               WHEN BHISTRESPPROVA.CODRESPOSTA = 'C' THEN 1
             END) * 3                       AS 'C',
       Count(CASE
               WHEN BHISTRESPPROVA.CODRESPOSTA = 'D' THEN 1
             END) * 2                       AS 'D',
       Count(CASE
               WHEN BHISTRESPPROVA.CODRESPOSTA = 'E' THEN 1
             END) * 1                       AS 'E'
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
       JOIN PPESSOA
         ON PPESSOA.CODIGO = BHISTORICO.CODPESSOA
       JOIN SALUNO
         ON PPESSOA.CODIGO = SALUNO.CODPESSOA
       JOIN SMATRICPL
         ON SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA
            AND SMATRICPL.RA = SALUNO.RA
       JOIN SHABILITACAOFILIAL
         ON SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
       JOIN SPLETIVO(NOLOCK)
         ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
WHERE  BHISTORICO.CODPROVA = :CODPROVA
       AND BOBJETOAVALIADO.SEQOBJETOAVALIADO = :CODOBJETOAVALIADO1
       AND SHABILITACAOFILIAL.CODFILIAL = :FILIAL
       AND SHABILITACAOFILIAL.CODCOLIGADA = :COLIGADA
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND SMATRICPL.CODTURMA = :TURMA
       AND SPLETIVO.CODPERLET = :PERIODO
GROUP  BY BOBJETOAVALIADO.SEQOBJETOAVALIADO,
          BHISTORICO.CODQUESTAO,
          Cast(BQUESTAO.TEXTO AS VARCHAR(MAX))
ORDER  BY BOBJETOAVALIADO.SEQOBJETOAVALIADO,
          BHISTORICO.CODQUESTAO 
