SELECT DISTINCT STURMADISC.CODTURMA, SCURSO.NOME
FROM STURMADISC
    LEFT OUTER JOIN STURNO
    ON STURMADISC.CODCOLIGADA = STURNO.CODCOLIGADA
        AND STURMADISC.CODTURNO = STURNO.CODTURNO
    JOIN SMATRICULA
    ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
        AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
    JOIN SPLETIVO
    ON STURMADISC.CODCOLIGADA = SPLETIVO.CODCOLIGADA
        AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET
    JOIN SHABILITACAOFILIAL
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL= STURMADISC.IDHABILITACAOFILIAL
        JOIN SCURSO
        ON SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
        AND SHABILITACAOFILIAL.CODLCOLIGADA = SCURSO.CODCOLIGADA
WHERE  SMATRICULA.CODSTATUS IN ( 14, 9, 3 )
    AND STURMADISC.CODFILIAL = 1
    AND SPLETIVO.CODPERLET = '2023/1'
ORDER  BY STURMADISC.CODTURMA 
