SELECT P.CHAPA, PP.NOME, PF.NOME, PFR.CODCCUSTO, 
    CASE 
        WHEN P.CODSITUACAO = 'A' THEN 'Ativo'
        WHEN P.CODSITUACAO = 'D' THEN 'Demitido'
        WHEN P.CODSITUACAO = 'C' THEN 'Contrato de Trabalho Suspenso'
        WHEN P.CODSITUACAO = 'F' THEN 'Férias'
        WHEN P.CODSITUACAO = 'I' THEN 'Apos. por Incapacidade Permanente'
        WHEN P.CODSITUACAO = 'P' THEN 'Af.Previdência'
        WHEN P.CODSITUACAO = 'Q' THEN 'Prisão / Cárcere'
    END AS 'SITUAÇÃO'
FROM PFUNC P
    JOIN PPESSOA PP
    ON PP.CODIGO = P.CODPESSOA
    JOIN PFUNCAO PF
    ON PF.CODIGO = P.CODFUNCAO
        AND PF.CODCOLIGADA = P.CODCOLIGADA
    JOIN PFRATEIOFIXO PFR
    ON PFR.CODCOLIGADA = P.CODCOLIGADA
        AND PFR.CHAPA = P.CHAPA
WHERE P.CODSITUACAO != 'D'
ORDER BY 2
