SELECT TOP 10
   /* TP.IDPRD AS 'ID PRODUTO',
    TP.CODIGOPRD AS 'CODIGO PRODUTO',
    TP.NOMEFANTASIA AS 'NOME PRODUTO',
    TP.DESCRICAO AS 'DESCRICAO PRODUTO',
    CASE 
        WHEN  TP.TIPO = 'P' THEN 'PRODUTO'
        ELSE 'SERVIÇO'
    END,*/
    TPDEF.CODTB2FAT AS 'TIPO DE PRODUTO',
    TPDEF.CODTB3FAT AS 'GRUPO DO PRODUTO',
    CASE 
         WHEN TPDEF.CODTB4FAT IS NULL THEN '---'
         ELSE TPDEF.CODTB4FAT 
    END 'GRUPO DE ESTOQUE',
    TPDEF.CODTBORCAMENTO AS 'NATUREZA ORÇAMENTARIA',
    T3.*
FROM TPRODUTO TP
    JOIN TPRODUTODEF TPDEF
        ON TPDEF.IDPRD = TP.IDPRD
    JOIN TTB3 T3
        ON T3.CODCOLIGADA = TPDEF.CODCOLIGADA
            AND T3.CODTB3FAT = TPDEF.CODTB3FAT
SELECT *
FROM GLINKSREL
WHERE MASTERTABLE = 'TTB3'