SELECT
    CASE
            WHEN SPSUSUARIO.SEXO = 'M' THEN 'Masculino'
            WHEN SPSUSUARIO.SEXO = 'F' THEN 'Feminino'
        END                                 AS 'Sexo',
    convert(varchar, SPSUSUARIO.DTNASCIMENTO, 101) AS 'Data de Nascimento',
    FLOOR(DATEDIFF(DAY, SPSUSUARIO.DTNASCIMENTO, GETDATE()) / 365.25) AS 'Idade em anos',
    SPSUSUARIO.CIDADE as 'Cidade',
    CASE 
        WHEN SPSINSCRICAOAREAOFERTADA.IDLAN IS NULL THEN 0
        ELSE '" "' + SPSINSCRICAOAREAOFERTADA.IDLAN 
    END AS 'Forma de Pagamento',
    CASE
            WHEN SPSINSCRICAOAREAOFERTADA.STATUS = 0 THEN 'Pendente Pagamento'
            WHEN SPSINSCRICAOAREAOFERTADA.STATUS = 1 THEN 'Inscrição Confirmada'
            WHEN SPSINSCRICAOAREAOFERTADA.STATUS = 8 THEN 'Inscrição Cancelada'
        END                                    AS 'Status da Inscrição',
    PCODESTCIVIL.DESCRICAO AS 'Estado Civil',
    PCODINSTRUCAO.DESCRICAO AS 'Escolaridade',
    CASE 
        WHEN (SELECT SHABILITACAOFILIAL.CODCURSO
    FROM SALUNO
        JOIN SHABILITACAOALUNO
        ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
            AND SHABILITACAOALUNO.RA = SALUNO.RA
        JOIN SHABILITACAOFILIAL
        ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
            AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    WHERE SALUNO.RA LIKE 'E23-1-18822%') = 'E12' THEN (SELECT
        CASE 
        WHEN SCONTRATO.CODPLANOPGTO = 'PRE-BOLETO' THEN 'Boleto' 
        ELSE 'Cartão de Crédito' 
    END
    FROM SCONTRATO
    WHERE SCONTRATO.RA LIKE 'E23-1-18822%') 
    END as 'Forma de Pagamento'
FROM SPSINSCRICAOAREAOFERTADA(NOLOCK)
    JOIN SPSUSUARIO(NOLOCK)
    ON SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
    JOIN SPSOPCAOINSCRITO(NOLOCK)
    ON SPSOPCAOINSCRITO.CODCOLIGADA = SPSINSCRICAOAREAOFERTADA.CODCOLIGADA
        AND SPSOPCAOINSCRITO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
        AND SPSOPCAOINSCRITO.NUMEROINSCRICAO = SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO
    JOIN SPSAREAOFERTADA(NOLOCK)
    ON SPSOPCAOINSCRITO.CODCOLIGADA = SPSAREAOFERTADA.CODCOLIGADA
        AND SPSOPCAOINSCRITO.IDPS = SPSAREAOFERTADA.IDPS
        AND SPSOPCAOINSCRITO.IDAREAINTERESSE = SPSAREAOFERTADA.IDAREAINTERESSE
    JOIN SPSAREAINTERESSE(NOLOCK)
    ON SPSAREAINTERESSE.IDAREAINTERESSE = SPSAREAOFERTADA.IDAREAINTERESSE
    JOIN PPESSOA(NOLOCK)
    ON PPESSOA.CODIGO = SPSUSUARIO.CODPESSOA
    JOIN PCODINSTRUCAO(NOLOCK)
    ON PPESSOA.GRAUINSTRUCAO = PCODINSTRUCAO.CODCLIENTE
    JOIN PCODESTCIVIL(NOLOCK)
    ON PCODESTCIVIL.CODCLIENTE = PPESSOA.ESTADOCIVIL
WHERE  SPSINSCRICAOAREAOFERTADA.IDPS = 78