SELECT DISTINCT PPESSOA.NOME,
       STURMADISC.CODTURMA
FROM   SMATRICULA
       JOIN STURMADISC
         ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
            AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
       JOIN SALUNO
         ON SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA
            AND SMATRICULA.RA = SALUNO.RA
       JOIN SPESSOA
         ON SALUNO.CODPESSOA = SPESSOA.CODIGO
       JOIN PPESSOA
         ON SPESSOA.CODIGO = PPESSOA.CODIGO
       JOIN SPLETIVO
         ON STURMADISC.CODCOLIGADA = SPLETIVO.CODCOLIGADA
            AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET
WHERE  SMATRICULA.CODSTATUS IN ( 14, 9, 3 )
       AND STURMADISC.CODFILIAL = 1
       AND STURMADISC.CODTURMA = 'ADM7ANA'
       AND SPLETIVO.CODPERLET = '2023/1'
ORDER BY 2,
1
