SELECT DISTINCT
    SMATRICPL.RA                               AS 'MATRICULA',
    PPESSOA.NOME AS 'NOME_ALUNO',
    SCURSO.NOME                                AS 'CURSO',
    CONVERT(VARCHAR(10),SMATRICPL.DTMATRICULA, 103)AS 'DATA DE MATRICULA',
    SSTATUS.DESCRICAO                          AS 'STATUS',
    ISNULL(SMATRICPL.CODTURMA, 'NÃO HÁ TURMA') AS' CODIGO_DA_TURMA'
FROM PPESSOA (NOLOCK)
    INNER JOIN SALUNO (NOLOCK)
    ON PPESSOA.CODIGO = SALUNO.CODPESSOA
    INNER JOIN SMATRICPL (NOLOCK)
    ON SALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
        AND SALUNO.RA = SMATRICPL.RA
    INNER JOIN SHABILITACAOFILIAL (NOLOCK)
    ON SMATRICPL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
    INNER JOIN SCURSO (NOLOCK)
    ON SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA
        AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
    INNER JOIN SSTATUS (NOLOCK)
    ON SMATRICPL.CODCOLIGADA = SSTATUS.CODCOLIGADA
        AND SMATRICPL.CODSTATUS = SSTATUS.CODSTATUS
    INNER JOIN SPLETIVO (NOLOCK)
    ON SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
        AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
    INNER JOIN SCONTRATO (NOLOCK)
    ON SCONTRATO.CODCOLIGADA = SALUNO.CODCOLIGADA
        AND SCONTRATO.RA = SALUNO.RA
        AND SCONTRATO.IDPERLET = SPLETIVO.IDPERLET
WHERE  SPLETIVO.IDPERLET = 102
    AND SPLETIVO.CODTIPOCURSO = 1
    AND SPLETIVO.CODFILIAL = 1
ORDER  BY PPESSOA.NOME 
