SELECT PFUNC.CHAPA                 AS 'CHAPA',
       PPESSOA.NOME                AS 'NOME',
       PSECAO.DESCRICAO            AS 'SETOR',
       CASE
         WHEN PFUNC.CODFILIAL = 1 THEN 'UNIATENAS'
         WHEN PFUNC.CODFILIAL = 2 THEN 'FACULDADE ATENAS - SETE LAGOAS/MG'
         WHEN PFUNC.CODFILIAL = 3 THEN 'FACULDADE ATENAS - PASSOS/MG'
         WHEN PFUNC.CODFILIAL = 5 THEN 'FACULDADE ATENAS - VALENÇA/BA'
         WHEN PFUNC.CODFILIAL = 6 THEN 'FACULDADE ATENAS - SORRISO/MT'
         WHEN PFUNC.CODFILIAL = 7 THEN 'FACULDADE ATENAS - PORTO SEGURO/BA'
       END                         'EMPRESA/CAMPUS',
       ROW_NUMBER()
         OVER (
           ORDER BY PPESSOA.NOME ) row_num
FROM   VTURMA
       JOIN PPESSOA
         ON VTURMA.CODPESSOA = PPESSOA.CODIGO
       LEFT JOIN PFUNC
              ON VTURMA.CODPESSOA = PFUNC.CODPESSOA
       JOIN PSECAO
         ON PSECAO.CODIGO = PFUNC.CODSECAO
WHERE  VTURMA.CODCOLIGADA = 1
       AND CODTURMA = :CODTURMA
       AND PFUNC.CODSITUAÇÃO IN ( 'A', 'Z' )
ORDER  BY PPESSOA.NOME 
