SELECT DISTINCT  PPESSOA.NOME, PSECAO.DESCRICAO, VCURSOS.NOMECURSO, VCURSOS.CARGAHORARIA FROM VCURSOS 
    JOIN VTURMAS 
        ON VTURMAS.CODCOLIGADA = VCURSOS.CODCOLIGADA
        AND VTURMAS.CODCURSO = VCURSOS.CODCURSO
    JOIN VTURMA
        ON VTURMA.CODCOLIGADA = VTURMAS.CODCOLIGADA
        AND VTURMA.CODTURMA = VTURMAS.CODTURMA
    JOIN PFUNC
        ON PFUNC.CODPESSOA = VTURMA.CODPESSOA
    JOIN PPESSOA
        ON PPESSOA.CODIGO = PFUNC.CODPESSOA
    JOIN PSECAO
        ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
        AND PSECAO.CODIGO = PFUNC.CODSECAO
WHERE VCURSOS.CODCURSO = 14
AND (PSECAO.DESCRICAO NOT LIKE ('%docentes%'))
AND PFUNC.CODSITUACAO = 'A'
ORDER BY PPESSOA.NOME