SELECT BHISTORICO.CODPESSOA,
       (SELECT NOME
        FROM   PPESSOA P
        WHERE  P.CODIGO = BHISTORICO.CODPESSOA) AS 'NOME',
       STURMADISC.CODTURMA                      AS 'TURMA',
       1                                        AS 'TOTAL'
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN SPROFESSOR (NOLOCK)
         ON SPROFESSOR.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND SPROFESSOR.CODPROF = SOBJETOAVALIADO.CODPROF
       JOIN PPESSOA (NOLOCK)
         ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
       JOIN SPROFESSORFILIAL (NOLOCK)
         ON SPROFESSORFILIAL.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
            AND SPROFESSORFILIAL.CODPROF = SPROFESSOR.CODPROF
       JOIN STURMADISC (NOLOCK)
         ON STURMADISC.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND STURMADISC.IDTURMADISC = SOBJETOAVALIADO.IDTURMADISC
       JOIN SPLETIVO (NOLOCK)
         ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
            AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
       JOIN STURMA(NOLOCK)
         ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
            AND STURMA.IDPERLET = STURMADISC.IDPERLET
            AND STURMA.CODFILIAL = STURMADISC.CODFILIAL
            AND STURMA.CODTURMA = STURMADISC.CODTURMA
WHERE  SPLETIVO.CODPERLET = :PERIODO
       AND SPROFESSORFILIAL.CODFILIAL = :FILIAL
       AND BHISTORICO.CODPROVA = :PROVA
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND STURMADISC.CODTIPOCURSO = :TIPO_CURSO
/* AND BHISTORICO.CODPESSOA IS NOT NULL*/
GROUP  BY STURMADISC.CODTURMA,
          BHISTORICO.CODPESSOA
ORDER  BY STURMADISC.CODTURMA,
          (SELECT NOME
           FROM   PPESSOA P
           WHERE  P.CODIGO = BHISTORICO.CODPESSOA) 
