SELECT DISTINCT SMATRICPL.CODTURMA,
                SALUNO.RA    AS 'MATRICULA DO ALUNO',
                PPESSOA.NOME AS 'NOME DO ALUNO',
                1            AS 'QUANTIDADE'
FROM   SOBJETOAVALIADO (NOLOCK)
       JOIN BOBJETOAVALIADO (NOLOCK)
         ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTORICO
         ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
            AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
            AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
       JOIN BHISTRESPPROVA (NOLOCK)
         ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
            AND BHISTRESPPROVA.ID = BHISTORICO.ID
            AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
            AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
            AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
       JOIN BPROVA (NOLOCK)
         ON BPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
            AND BPROVA.CODPROVA = BHISTORICO.CODPROVA
       JOIN BQUESTAO (NOLOCK)
         ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
            AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
            AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
            AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
       JOIN PPESSOA
         ON PPESSOA.CODIGO = BHISTORICO.CODPESSOA
       JOIN SALUNO
         ON PPESSOA.CODIGO = SALUNO.CODPESSOA
       JOIN SMATRICPL
         ON SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA
            AND SMATRICPL.RA = SALUNO.RA
       JOIN SHABILITACAOFILIAL
         ON SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
       JOIN STURMADISC(NOLOCK)
         ON STURMADISC.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
            AND STURMADISC.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
       JOIN SCURSO(NOLOCK)
         ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
            AND SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
       JOIN SPLETIVO(NOLOCK)
         ON SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
            AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
WHERE  BHISTORICO.CODPROVA = :CODPROVA
       AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
       AND SHABILITACAOFILIAL.CODFILIAL = :CODFILIAL
       AND SHABILITACAOFILIAL.CODCURSO = :CODCURSO
       AND SPLETIVO.CODPERLET = :CODPERLET
       AND SHABILITACAOFILIAL.CODTIPOCURSO = :CODTIPOCURSO
ORDER  BY 3 
