SELECT PFUNC.CHAPA AS 'Chapa',
    PPESSOA.NOME AS 'Nome',
    PFUNCAO.NOME AS 'Função',
    PSECAO.DESCRICAO AS 'Setor',
    1 as 'Quantidade'
FROM PFUNC
    JOIN PPESSOA
    ON PPESSOA.CODIGO = PFUNC.CODPESSOA
    JOIN PSECAO
    ON PSECAO.CODIGO = PFUNC.CODSECAO
        AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
    JOIN PFUNCAO
    ON PFUNCAO.CODIGO = PFUNC.CODFUNCAO
        AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
WHERE
    PFUNC.CODFILIAL = 01
    AND PFUNC.CODSITUACAO != 'D'
ORDER BY 
    PPESSOA.NOME