SELECT BQUESTAO.CODQUESTAO,
    CASE 
        WHEN Cast(BMEMO.VALMEMO AS VARCHAR(MAX)) = ''
            THEN 'Em branco' 
        ELSE Cast(BMEMO.VALMEMO AS VARCHAR(MAX)) 
    END AS 'Resposta',
    COUNT(*) AS 'Quantidade'
FROM SOBJETOAVALIADO (NOLOCK)
    JOIN BOBJETOAVALIADO (NOLOCK)
    ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
    JOIN BHISTORICO
    ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
        AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
        AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
    JOIN BHISTRESPPROVA (NOLOCK)
    ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
        AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
        AND BHISTRESPPROVA.ID = BHISTORICO.ID
        AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
        AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
        AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
    JOIN BQUESTAO (NOLOCK)
    ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
        AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
        AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
        AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
    JOIN BMEMO (NOLOCK)
    ON BMEMO.ID = BHISTRESPPROVA.IDMEMORESPABERTA
WHERE  BHISTORICO.CODPROVA = 42
    AND BQUESTAO.CODQUESTAO= 01

GROUP BY
    Cast(BQUESTAO.TEXTO AS VARCHAR(MAX)),
    BQUESTAO.CODQUESTAO,
    Cast(BMEMO.VALMEMO AS VARCHAR(MAX))
