SELECT PFUNC.CHAPA, PPESSOA.NOME, PSECAO.DESCRICAO,
    ROW_NUMBER()
         OVER (
           ORDER BY PPESSOA.NOME ) row_num
FROM VTURMA
    JOIN PPESSOA
    ON VTURMA.CODPESSOA = PPESSOA.CODIGO
    JOIN PFUNC
    ON PFUNC.CODPESSOA = PPESSOA.CODIGO
    JOIN PSECAO
    ON PSECAO.CODIGO = PFUNC.CODSECAO
        AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
WHERE  VTURMA.CODTURMA = 87
    AND PFUNC.CODSITUAÇÃO = 'A'
    AND PSECAO.DESCRICAO != 'DOCENTES'
    AND PFUNC.CODFILIAL = 01
ORDER  BY PPESSOA.NOME