SELECT DISTINCT  PPESSOA.NOME       AS 'NOME DO ALUNO',
    SCURSO.NOME        AS 'CURSO',
    1                  AS 'TOTAL'
FROM SOBJETOAVALIADO (NOLOCK)
    JOIN BOBJETOAVALIADO (NOLOCK)
    ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
    JOIN BHISTORICO
    ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
        AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
        AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
    JOIN BHISTRESPPROVA (NOLOCK)
    ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
        AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
        AND BHISTRESPPROVA.ID = BHISTORICO.ID
        AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
        AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
        AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
    JOIN PPESSOA
    ON PPESSOA.CODIGO = BHISTORICO.CODPESSOA
    JOIN STURMADISC (NOLOCK)
    ON STURMADISC.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
        AND STURMADISC.IDTURMADISC = SOBJETOAVALIADO.IDTURMADISC
    JOIN SPLETIVO (NOLOCK)
    ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
    JOIN STURMA(NOLOCK)
    ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND STURMA.IDPERLET = STURMADISC.IDPERLET
        AND STURMA.CODFILIAL = STURMADISC.CODFILIAL
        AND STURMA.CODTURMA = STURMADISC.CODTURMA
    JOIN SHABILITACAOFILIAL(NOLOCK)
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
    JOIN SCURSO(NOLOCK)
    ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
        JOIN SHABILITACAOALUNO(NOLOCK)
        ON SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
WHERE /* BHISTORICO.CODPROVA = 14
       AND */BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
    AND SHABILITACAOFILIAL.CODFILIAL = 01
    AND SPLETIVO.CODPERLET = '2023/1'
    AND SHABILITACAOFILIAL.CODTIPOCURSO = 01
    AND scurso.CODCURSO = '07'
    AND SHABILITACAOALUNO.CODSTATUS NOT IN (10, 15, 16, 17)
ORDER BY 2
