SELECT DISTINCT BHISTORICO.CODPESSOA,
    SALUNO.RA,
    (SELECT NOME
    FROM PPESSOA P
    WHERE  P.CODIGO = BHISTORICO.CODPESSOA) AS 'NOME',
    SCURSO.NOME                      AS 'CURSO',
    1                                        AS 'TOTAL'
FROM SOBJETOAVALIADO (NOLOCK)
    JOIN BOBJETOAVALIADO (NOLOCK)
    ON SOBJETOAVALIADO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
    JOIN BHISTORICO
    ON BHISTORICO.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
        AND BHISTORICO.SEQOBJETOAVALIADO = SOBJETOAVALIADO.SEQOBJETOAVALIADO
        AND BHISTORICO.SEQOBJETOAVALIADO = BOBJETOAVALIADO.SEQOBJETOAVALIADO
    JOIN BHISTRESPPROVA (NOLOCK)
    ON BHISTRESPPROVA.CODCOLIGADA = BHISTORICO.CODCOLIGADA
        AND BHISTRESPPROVA.CODPROVA = BHISTORICO.CODPROVA
        AND BHISTRESPPROVA.ID = BHISTORICO.ID
        AND BHISTRESPPROVA.CODAREA = BHISTORICO.CODAREA
        AND BHISTRESPPROVA.CODMATERIA = BHISTORICO.CODMATERIA
        AND BHISTRESPPROVA.CODQUESTAO = BHISTORICO.CODQUESTAO
    JOIN SPROFESSOR (NOLOCK)
    ON SPROFESSOR.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
        AND SPROFESSOR.CODPROF = SOBJETOAVALIADO.CODPROF
    JOIN PPESSOA (NOLOCK)
    ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
    JOIN BQUESTAO (NOLOCK)
    ON BHISTORICO.CODCOLIGADA = BQUESTAO.CODCOLIGADA
        AND BHISTORICO.CODAREA = BQUESTAO.CODAREA
        AND BHISTORICO.CODMATERIA = BQUESTAO.CODMATERIA
        AND BHISTORICO.CODQUESTAO = BQUESTAO.CODQUESTAO
    JOIN SPROFESSORFILIAL (NOLOCK)
    ON SPROFESSORFILIAL.CODCOLIGADA = SPROFESSOR.CODCOLIGADA
        AND SPROFESSORFILIAL.CODPROF = SPROFESSOR.CODPROF
    JOIN STURMADISC (NOLOCK)
    ON STURMADISC.CODCOLIGADA = SOBJETOAVALIADO.CODCOLIGADA
        AND STURMADISC.IDTURMADISC = SOBJETOAVALIADO.IDTURMADISC
    JOIN SPLETIVO (NOLOCK)
    ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
    JOIN STURMA(NOLOCK)
    ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND STURMA.IDPERLET = STURMADISC.IDPERLET
        AND STURMA.CODFILIAL = STURMADISC.CODFILIAL
        AND STURMA.CODTURMA = STURMADISC.CODTURMA
    JOIN SHABILITACAOFILIAL(NOLOCK)
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
        AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
    JOIN SCURSO(NOLOCK)
    ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
    JOIN SHABILITACAOALUNO(NOLOCK)
    ON SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
        AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
        JOIN SALUNO(NOLOCK)
        ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
        AND SALUNO.RA = SHABILITACAOALUNO.RA
WHERE  SPLETIVO.CODPERLET = '2023/1'
    AND SPROFESSORFILIAL.CODFILIAL = 01
    --AND BHISTORICO.CODPROVA = 14
    AND BHISTRESPPROVA.CODRESPOSTA IS NOT NULL
    AND STURMADISC.CODTIPOCURSO = 01
    AND SCURSO.CODCURSO = '07'

/* AND BHISTORICO.CODPESSOA IS NOT NULL*/
GROUP  BY STURMADISC.CODTURMA,
          BHISTORICO.CODPESSOA,
          SALUNO.RA,
          SCURSO.NOME

