select DISTINCT GUSRPERFIL.CODUSUARIO, GCOLIGADA.NOME, GSISTEMA.DESCRICAO, GUSRPERFIL.CODPERFIL,GSISTEMA.CODSISTEMA ,GUSRPERFIL.CODSISTEMA
from GUSRPERFIL
JOIN GSISTEMA
     ON GSISTEMA.CODSISTEMA = GUSRPERFIL.CODSISTEMA
JOIN GCOLIGADA
     ON GCOLIGADA.CODCOLIGADA = GUSRPERFIL.CODCOLIGADA
JOIN GPERFIL
    ON GPERFIL.CODPERFIL = GUSRPERFIL.CODPERFIL
WHERE --GUSRPERFIL.CODUSUARIO = 'ana.brod' 
--OR GUSRPERFIL.CODUSUARIO = 'antonio.filho' OR
-- GUSRPERFIL.CODUSUARIO = 'stenia.santos' OR 
GUSRPERFIL.CODUSUARIO = 'weslem.amorim' 
AND GCOLIGADA.CODCOLIGADA = 01
ORDER BY GUSRPERFIL.CODUSUARIO
