
SELECT CONCAT(SPARCELA.PARCELA ,'ª') AS 'DESCRIÇÃO' ,
    CONCAT('R$ ', CAST((SPARCELA.VALOR - SPARCELA.VALOR * 40 / 100) AS DECIMAL(10, 2))) AS 'VALOR_MENSALIDADE',
    FORMAT(SPARCELA.DTVENCIMENTO, 'MM/yyyy') AS 'DTVENCIMENTO',
    CONCAT(CAST((SELECT SBOLSAALUNO.DESCONTO
    FROM sbolsa
        JOIN sbolsaaluno ON sbolsaaluno.CODBOLSA = sbolsa.CODBOLSA
        JOIN SPARCELA ON SPARCELA.CODCONTRATO = SBOLSAALUNO.CODCONTRATO
            AND SPARCELA.IDPERLET = SBOLSAALUNO.IDPERLET
            AND SPARCELA.RA = SBOLSAALUNO.RA
    WHERE nome LIKE 'cred atenas%'
        AND SBOLSAALUNO.ra = '22-1-18377'
        AND SPARCELA.CODSERVICO = 1
        AND sbolsaaluno.CODCONTRATO = 92470
        AND SPARCELA.PARCELA = 2) AS DECIMAL(10, 2)), ' %') AS '%',
    CAST((SPARCELA.VALOR - SPARCELA.VALOR * 40 / 100) - ((SPARCELA.VALOR - SPARCELA.VALOR * 40 / 100) * (SELECT SBOLSAALUNO.DESCONTO
    FROM sbolsa
        JOIN sbolsaaluno ON sbolsaaluno.CODBOLSA = sbolsa.CODBOLSA
        JOIN SPARCELA ON SPARCELA.CODCONTRATO = SBOLSAALUNO.CODCONTRATO
            AND SPARCELA.IDPERLET = SBOLSAALUNO.IDPERLET
            AND SPARCELA.RA = SBOLSAALUNO.RA
    WHERE nome LIKE 'cred atenas%'
        AND SBOLSAALUNO.ra = '22-1-18377'
        AND SPARCELA.CODSERVICO = 1
        AND sbolsaaluno.CODCONTRATO = 92470
        AND SPARCELA.PARCELA = 2) / 100) AS DECIMAL(10, 2)) AS 'VALOR_PARCELA'
FROM sbolsa
    JOIN sbolsaaluno ON sbolsaaluno.CODBOLSA = sbolsa.CODBOLSA
    JOIN SPARCELA ON SPARCELA.CODCONTRATO = SBOLSAALUNO.CODCONTRATO
        AND SPARCELA.IDPERLET = SBOLSAALUNO.IDPERLET
        AND SPARCELA.RA = SBOLSAALUNO.RA
WHERE nome NOT LIKE 'cred atenas%'
    AND SBOLSAALUNO.ra = '22-1-18377'
    AND SPARCELA.CODSERVICO = 1
    AND sbolsaaluno.CODCONTRATO = 92470
ORDER BY SPARCELA.PARCELA
